### ISSUE TITLE
Release Specific Version 

### ISSUE THREAD

**Issue by Mom0aut** [xbranch/ngitflow#6]
Hello,

is it possible to release a specific version like: ngitflow release start version 1.0.15

thank u

**Comment by schilzx** [comment]
Please take a look at `2.0.3-snapshot.1` and [README.md](https://github.com/xbranch/ngitflow#release) You can simply install it with `npm i -D ngitflow@2.0.3-snapshot.1`.

Example:
```
ngitflow release start 1.15.0
```
